### ISSUE TITLE
Table inside array of tables not working

### ISSUE THREAD

**Issue by petersondrew** [paiden/Nett#2]
I have the following sample code:
```csharp
public class CustomDictionary : Dictionary<string, string>
{
	public CustomDictionary(IDictionary<string, string> collection) : base(collection)
	{
	}
	
	public CustomDictionary() : base()
	{
	}
}

public interface IBar
{
    string Buzz { get; }
    CustomDictionary Dict { get; }
}

public interface IFoo
{
    string Name { get; }
    CustomDictionary Dict { get; }
    List<IBar> AList { get; }
}

public class Foo : IFoo
{
    public string Name { get; set; }
    public CustomDictionary Dict { get; set; }
    public List<IBar> AList { get; set; }
	
	public Foo(string name, CustomDictionary dict, List<IBar> list)
	{
		Name = name;
		Dict = dict;
		AList = list;
	}
}

public class Bar : IBar
{
    public string Buzz { get; set; }
    public CustomDictionary Dict { get; set; }
	
	public Bar(string buzz, CustomDictionary dict)
	{
		Buzz = buzz;
		Dict = dict;
	}
}

void Main()
{
	var config = TomlConfig.Create().ConfigureType<CustomDictionary>().As.ConvertTo<TomlTable>().As(
           collection =>
           {
               var table = new TomlTable();
               foreach (var kvp in collection.OrderBy(kvp => kvp.Key))
               {
                   table.Add(kvp.Key, new TomlString(kvp.Value));
               }
               return table;
           }).And.ConvertFrom<TomlTable>().As(table =>
           {
               var collection = new CustomDictionary();
               foreach (var kvp in table.ToDictionary())
               {
                   collection.Add(kvp.Key, kvp.Value as string);
               }
               return collection;
           }).Apply();
	
	var exampleDict = new CustomDictionary {{"CustomKey1", "CustomValue1"}, {"CustomKey2", "CustomValue2"}};
	var barList = new List<IBar>();
	barList.Add(new Bar("buzzbuzz", exampleDict));
	barList.Add(new Bar("foofoo", exampleDict));
	var test = new Foo("Test", exampleDict, barList);
		   
	Console.WriteLine(Toml.WriteString(test, config));
}
```
When serializing, I get TOML that looks like the following:
```toml
Name = "Test"

[Dict]
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"

[[AList]]
Buzz = "buzzbuzz"
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"


[[AList]]
Buzz = "foofoo"
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"
```
But based on the v0.4 specification, I would expect to see output like this:
```toml
Name = "Test"

[Dict]
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"

[[AList]]
Buzz = "buzzbuzz"
[Dict]
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"


[[AList]]
Buzz = "foofoo"
[Dict]
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"
```
I haven't dug in to find what's going on yet so I don't know if it's an issue with implementing the spec, or if it's a bug specifically due to the custom converter. See [here](https://github.com/toml-lang/toml#array-of-tables) for an example in the spec.
Thanks!

**Comment by paiden** [comment]
Thanks for reporting this issue. Should be fixed with the associated commit.

**Comment by petersondrew** [comment]
It does properly serialize to TOML now, but fails to deserialize with the error "Failed to add new table because the target table already contains a row with the key 'Dict' of type 'table'." which appears to be coming from `ExpressionsProduction.TryApply`

**Comment by petersondrew** [comment]
It appears that it's attempting to add the Dict key to the "base" table, rather than the `[[AList]]` table array.

**Comment by petersondrew** [comment]
It looks as though this is because `TomlTableProduction.TryApply(tokens)` notices that `CustomKey1` is a part of the `[Dict]` table at the root and returns before looking further to find that it's also associated with the `[Dict]` table underneath the `[[AList]]` table array

**Comment by petersondrew** [comment]
It appears that when parsing, the `KeyProduction.Apply` assumes that keys are unique within the file

**Comment by paiden** [comment]
Hi. I think the last 'fix' was done a little bit hasty.

I quickly re-read the TOML spec and it seems indeed that the example you gave should serialize as  
```toml
Name = "Test"

[Dict]
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"

[[AList]]
Buzz = "buzzbuzz"
[AList.Dict]
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"


[[AList]]
Buzz = "foofoo"
[AList.Dict]
CustomKey1 = "CustomValue1"
CustomKey2 = "CustomValue2"
```
to be correct. 

I will reopen the bug and hopefully fix it correctly this time (unfortunately the able array spec is a little bit vague in some aspects IMO) within the next view days.
