### ISSUE TITLE
Inline Table bug

### ISSUE THREAD

**Issue by Splamy** [paiden/Nett#51]
I'm using `0.9.0` from nuget

This small example:
```csharp
public static void Main()
{
	var table = Toml.Create();
	var root = table.Add("Root", new object(), TomlTable.TableTypes.Default);
	root.Add("A", new object(), TomlTable.TableTypes.Default);
	root.Add("B", new object(), TomlTable.TableTypes.Inline);
	Toml.WriteFile(table, "test.toml");
}
```

produces:
```toml
[Root]

[Root.A]
B = {  }
```
which now means `B` has the path `Root.A.B`

I would expect:
```toml
[Root]
B = {  }

[Root.A]
```
where `B` was added to `Root` and has the path `Root.B`.

When using `Default` instead of `Inline` it correctly produces
```toml
[Root]

[Root.A]

[Root.B]
```
