### ISSUE TITLE
Nested tables supported?

### ISSUE THREAD

**Issue by aggieben** [paiden/Nett#73]
I'm trying to parse a toml string like

```
[[thing]]
  name = "channel1"

  [[property]]
    name = "property1"
```

with a model, and Nett doesn't seem to want to seem to resolve the members of the model properly or something.  Here's my LinqPad script:

![image](https://user-images.githubusercontent.com/1321/53669319-55ff2680-3c3c-11e9-8104-8436b56e8233.png)

Does my test look reasonable?  Is there something I'm not doing that would make this work?

**Comment by Splamy** [comment]
Toml doesnt work by indentation, you'd have to write:
```toml
[[thing]]
  name = "channel1"

[[thing.property]]
    name = "property1"
```
